version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: group4321
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "group4@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "group4321"
    ports:
      - "80:80"
    depends_on:
      - postgres

  db_init:
    image: postgres
    depends_on:
      - postgres
    volumes:
      - ./src/Database/Script:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: group4321
      POSTGRES_DB: mydatabase
    entrypoint: ["sh", "-c", "until pg_isready -h postgres; do sleep 2; done; PGPASSWORD=$$POSTGRES_PASSWORD psql -h postgres -U $$POSTGRES_USER -d $$POSTGRES_DB -f /docker-entrypoint-initdb.d/DbCreation.sql"]

volumes:
  pgdata:
